### ISSUE TITLE
Post an APK under "Releases"

### ISSUE THREAD

**Issue by johnzeringue** [CIRDLES/CHRONI-Android#1]
GitHub repos have pages for releases that allow you to upload binaries. You never want to version control binaries, because it makes your repo big and bulky. However, making releases is convenient for users who want to test your app with installing the whole Android development environment. You also advertise an APK in the wiki's setup page that's not linked and not anywhere on GitHub. Let me know if you need any help doing it.

**Comment by JoyeNettles** [comment]
I'm on it now! I will let you know if I have any questions!
