### ISSUE TITLE
Formatting refinements

### ISSUE THREAD

**Issue by bowring** [CIRDLES/CHRONI-Android#90]
CHRONI needs to be able to handle all the formatting specifications provided in report settings beyond the defaults currently handled.

**Comment by johnzeringue** [comment]
@gabriellecozart, you probably want to go through and identify each of the missing formatting specifications in a new issue. The issue tracker isn't hugely beneficial when you only have "big idea" issues like this one. Ideally, you want it full of "afternoon fixes".

**Comment by bowring** [comment]
A good starting place is the schema, particularly the column schema, all found at http://earth-time.org/projects/upb/public_data/XSD/upbReports/ .
